version: '3.7'

services:
  api:
    image: eassbhhtgu/networkdiscoveryapi:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet NetworkDiscoveryApi.WebApplication.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_Kestrel__Certificates__Default__KeyPath: /run/secrets/localhost.key
      ASPNETCORE_Kestrel__Certificates__Default__Path: /run/secrets/localhost.crt
      ASPNETCORE_HTTPS_PORT: '443'
      ASPNETCORE_URLS: https://+
      Aliases:keylight: 3c6a9d14d765
      Aliases:lightstrip: 3c6a9d187071
      Aliases:vr front: 28ee52eb0aa4
      Aliases:vr rear: 003192e1a474
      Aliases:philipshue: ecb5fa18e324
      Aliases:philipshuebridge: ecb5fa18e324
      Aliases:globalcache: 000c1e059cad
      Aliases:irblaster: 000c1e059cad
      Identity:Authority: https://identityserver/
      Identity:Scope: networkdiscovery
      Router:Host: 192.168.1.10
      Router:PathToPrivateKey: /run/secrets/id_rsa
      Router:Port: 22
      Router:Username: root
    ports:
    - 40443:443/tcp
    secrets:
    - source: id_rsa
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt
    - source: localhost.crt
    - source: localhost.key

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\networkdiscovery.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\networkdiscovery.key
