version: '3.7'

services:
  api:
    image: eassbhhtgu/networkdiscoveryapi:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: '443'
      ASPNETCORE_URLS: https://+
      Kestrel:Certificates:Default:KeyPath: /run/secrets/localhost.key
      Kestrel:Certificates:Default:Path: /run/secrets/localhost.crt
      Router:Host: 192.168.1.10
      Router:PathToPrivateKey: /run/secrets/id_rsa
      Router:Port: 22
      Router:Username: root
    ports:
    - 34786:443/tcp
    secrets:
    - source: id_rsa
    - source: localhost.crt
    - source: localhost.key

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
