version: '3.7'

services:
  api:
    image: eassbhhtgu/networkdiscoveryapi:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+
    ports:
    - 34785:80/tcp
    secrets:
    - source: id_rsa

secrets:
  id_rsa:
    file: ${USERPROFILE}\.ssh\id_rsa
